Las pruebas unitarias que nos permite python nos permiten corroborar que el código escrito este realizando las actividades asignadas correctamente, esto se debe, a que en ocasiones podemos programar con objetivos especificos esperando determinados comportamientos, sin embargo, el código puede que este realizando otras tareas, así, podemos que disminuir las fallas en nuestro código.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.set_option("display.max_columns",100)

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/kshedden/statswpy/master/NHANES/merged/nhanes_2015_2016.csv")
# Cambiar index

In [3]:
df.head()

,SEQN,ALQ101,ALQ110,ALQ130,SMQ020,RIAGENDR,RIDAGEYR,RIDRETH1,DMDCITZN,DMDEDUC2,DMDMARTL,DMDHHSIZ,WTINT2YR,SDMVPSU,SDMVSTRA,INDFMPIR,BPXSY1,BPXDI1,BPXSY2,BPXDI2,BMXWT,BMXHT,BMXBMI,BMXLEG,BMXARML,BMXARMC,BMXWAIST,HIQ210
1,83732,1.0,NaN,1.0,1,1,62,3,1.0,5.0,1.0,2,134671.37,1,125,4.39,128.0,70.0,124.0,64.0,94.8,184.5,27.8,43.3,43.6,35.9,101.1,2.0
2,83733,1.0,NaN,6.0,1,1,53,3,2.0,3.0,3.0,1,24328.56,1,125,1.32,146.0,88.0,140.0,88.0,90.4,171.4,30.8,38.0,40.0,33.2,107.9,NaN
3,83734,1.0,NaN,NaN,1,1,78,3,1.0,3.0,1.0,2,12400.01,1,131,1.51,138.0,46.0,132.0,44.0,83.4,170.1,28.8,35.6,37.0,31.0,116.5,2.0
4,83735,2.0,1.0,1.0,2,2,56,3,1.0,5.0,6.0,1,102718.00,1,131,5.00,132.0,72.0,134.0,68.0,109.8,160.9,42.4,38.5,37.7,38.3,110.1,2.0
5,83736,2.0,1.0,1.0,2,2,42,4,1.0,4.0,3.0,5,17627.67,2,126,1.23,100.0,70.0,114.0,54.0,55.2,164.9,20.3,37.4,36.0,27.2,80.4,2.0

### Objetivo

Queremos encontrar la media de las 100 primeras filas de 'BPXSY1' cuando 'RIDAGEYR' > 60

In [22]:
#pd.Series.mean(df[df.RIDAGEYR > 60].loc[range(0,100), df.BPXSY1]) 
# Esta línea de código no funciona, no se sabe aun por qué 

pd.Series.mean(df[df.RIDAGEYR>60].loc[0:100, "BPXSY1"])

139.57142857142858

In [46]:
#df[df.RIDAGEYR > 60].loc[:100, 'BPXSY1']
pd.Series.mean(df[df.RIDAGEYR>60].loc[:100,"BPXSY1"])

139.57142857142858

In [85]:
df.BPXSY1.iloc[:100][df.RIDAGEYR > 60].mean()

139.57142857142858

In [38]:
 # probar nuestro código en sólo diez filas para que podamos comprobar fácilmente

    
test = pd.DataFrame({"columna1": np.repeat([3,1],5),
                     "columna2":range(3,13)}, index=range(1,11)) 
test
# np.repeat([3,1],5) -> [3,1] son los valores a repetirse, 5 -> es el numero de veces que se repetirán
# la columna 2 debe con los valores repetidos, igual que el index



#test = pd.DataFrame({"columna1": np.repeat([3,1],1),"columna2":range(3,5)}, index=range(1,3)) 
#test
#Otra forma

    columna1  columna2
1          3         3
2          3         4
3          3         5
4          3         6
5          3         7
6          1         8
7          1         9
8          1        10
9          1        11
10         1        12

In [67]:
# repetimos la formula de arriba

pd.Series.mean(test[test.columna1>2].loc[0:5, "columna2"])

5.0

In [68]:
test[test.columna1>2].loc[0:5, "columna2"]
# Aqui deberia dar un error y que pandas automaticamente
# convirtiera los datos en un Nan cuando fueran menor a 2
# por ejemplo aqui el dato 0, de la fila 0 no existe, por eso deberia convertirlo en NaN

1    3
2    4
3    5
4    6
5    7
Name: columna2, dtype: int64

In [65]:
df[df.RIDAGEYR > 60].loc[:5, ]

,SEQN,ALQ101,ALQ110,ALQ130,SMQ020,RIAGENDR,RIDAGEYR,RIDRETH1,DMDCITZN,DMDEDUC2,DMDMARTL,DMDHHSIZ,WTINT2YR,SDMVPSU,SDMVSTRA,INDFMPIR,BPXSY1,BPXDI1,BPXSY2,BPXDI2,BMXWT,BMXHT,BMXBMI,BMXLEG,BMXARML,BMXARMC,BMXWAIST,HIQ210
1,83732,1.0,NaN,1.0,1,1,62,3,1.0,5.0,1.0,2,134671.37,1,125,4.39,128.0,70.0,124.0,64.0,94.8,184.5,27.8,43.3,43.6,35.9,101.1,2.0
3,83734,1.0,NaN,NaN,1,1,78,3,1.0,3.0,1.0,2,12400.01,1,131,1.51,138.0,46.0,132.0,44.0,83.4,170.1,28.8,35.6,37.0,31.0,116.5,2.0

In [80]:
#df[df.RIDAGEYR > 60].loc[range(0:5), :]
df[df.RIDAGEYR>60].loc[0:5,:]
# en el ejercicio esto no estaria bien

,SEQN,ALQ101,ALQ110,ALQ130,SMQ020,RIAGENDR,RIDAGEYR,RIDRETH1,DMDCITZN,DMDEDUC2,DMDMARTL,DMDHHSIZ,WTINT2YR,SDMVPSU,SDMVSTRA,INDFMPIR,BPXSY1,BPXDI1,BPXSY2,BPXDI2,BMXWT,BMXHT,BMXBMI,BMXLEG,BMXARML,BMXARMC,BMXWAIST,HIQ210
1,83732,1.0,NaN,1.0,1,1,62,3,1.0,5.0,1.0,2,134671.37,1,125,4.39,128.0,70.0,124.0,64.0,94.8,184.5,27.8,43.3,43.6,35.9,101.1,2.0
3,83734,1.0,NaN,NaN,1,1,78,3,1.0,3.0,1.0,2,12400.01,1,131,1.51,138.0,46.0,132.0,44.0,83.4,170.1,28.8,35.6,37.0,31.0,116.5,2.0

In [75]:
df[df.RIDAGEYR > 60].iloc[range(0,5),:]

,SEQN,ALQ101,ALQ110,ALQ130,SMQ020,RIAGENDR,RIDAGEYR,RIDRETH1,DMDCITZN,DMDEDUC2,DMDMARTL,DMDHHSIZ,WTINT2YR,SDMVPSU,SDMVSTRA,INDFMPIR,BPXSY1,BPXDI1,BPXSY2,BPXDI2,BMXWT,BMXHT,BMXBMI,BMXLEG,BMXARML,BMXARMC,BMXWAIST,HIQ210
1,83732,1.0,NaN,1.0,1,1,62,3,1.0,5.0,1.0,2,134671.37,1,125,4.39,128.0,70.0,124.0,64.0,94.8,184.5,27.8,43.3,43.6,35.9,101.1,2.0
3,83734,1.0,NaN,NaN,1,1,78,3,1.0,3.0,1.0,2,12400.01,1,131,1.51,138.0,46.0,132.0,44.0,83.4,170.1,28.8,35.6,37.0,31.0,116.5,2.0
6,83737,2.0,2.0,NaN,2,2,72,1,2.0,2.0,4.0,5,11252.31,1,128,2.82,116.0,58.0,122.0,58.0,64.4,150.0,28.6,34.4,33.5,31.4,92.9,NaN
14,83754,2.0,1.0,1.0,2,2,67,2,1.0,5.0,1.0,7,10495.87,1,128,0.89,124.0,76.0,116.0,64.0,117.8,164.1,43.7,34.8,38.6,42.7,123.0,2.0
15,83755,1.0,NaN,3.0,2,1,67,4,1.0,5.0,2.0,1,14080.10,1,126,2.04,132.0,84.0,136.0,82.0,97.4,183.8,28.8,42.5,40.6,34.2,106.3,2.0

In [126]:
# El ejercicio deberia dar con iloc, donde el
# index 0 de nulo y no cuente ese valor

pd.Series.mean(test[test.columna1>2].iloc[range(0,5), 1]) 
# el 1 indica que queremos la columna2, por el index de las columnas
# index de columna 1 = 0, index de columna2 = 1

5.0

In [149]:
pd.Series.mean(df[df.RIDAGEYR > 60].loc[df.iterrows(), 'BPXSY1'])

TypeError: unhashable type: 'Series'

In [157]:
np.array(df.loc[[range(0,5)],["RIDAGEYR"]],dtype=object)

KeyError: "None of [Index([(0, 1, 2, 3, 4)], dtype='object')] are in the [index]"

In [ ]:
x lambda x < 100